name: NASA Project CI
on:
  push: # runs when code is pushed to one of these branches
    branches: [main]
  pull_request:
    branches: [main]
# define jobs that will run when one of our two 'on' events are triggered
jobs: # workflow consists of one or more jobs
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js version 16
        uses: actions/setup-node@v2 # make sure that node is installed
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build --prefix client # run create-react-app script inside client folder
  # deploy:
  #   needs: build # deploy only runs if the build finishes
